{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/chainableexception\/cause"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/cause","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The direct cause of the exception."}],"kind":"symbol","metadata":{"role":"symbol","title":"cause","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:15ExpoModulesCore18ChainableExceptionP5causes5Error_pSgvp","required":true,"modules":[{"name":"ExpoModulesCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/cause":{"role":"symbol","title":"cause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The direct cause of the exception."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/cause","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/cause"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException":{"role":"symbol","title":"ChainableException","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChainableException"}],"abstract":[{"type":"text","text":"An exception that may have been caused by another error."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChainableException"}],"url":"\/documentation\/expomodulescore\/chainableexception"}}}