{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/chainableexception\/causedby(_:)-94h9t"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/causedBy(_:)-94h9t","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the direct cause of the exception and returns itself."}],"kind":"symbol","metadata":{"role":"symbol","title":"causedBy(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"symbolKind":"method","externalID":"s:15ExpoModulesCore18ChainableExceptionPAAE8causedByyxs5Error_pSgF","extendedModule":"ExpoModulesCore","modules":[{"name":"ExpoModulesCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/causedBy(_:)-8vil4"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/causedBy(_:)-94h9t":{"role":"symbol","title":"causedBy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets the direct cause of the exception and returns itself."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/causedBy(_:)-94h9t","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/causedby(_:)-94h9t"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException":{"role":"symbol","title":"ChainableException","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChainableException"}],"abstract":[{"type":"text","text":"An exception that may have been caused by another error."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChainableException"}],"url":"\/documentation\/expomodulescore\/chainableexception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/causedBy(_:)-8vil4":{"defaultImplementations":1,"role":"symbol","title":"causedBy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets the direct cause of the exception and returns itself."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/causedBy(_:)-8vil4","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/causedby(_:)-8vil4"}}}