{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/chainableexception\/rootcause-38jk7"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/rootCause-38jk7","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The first error that started the chain of exceptions."}],"kind":"symbol","metadata":{"role":"symbol","title":"rootCause","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:15ExpoModulesCore18ChainableExceptionPAAE9rootCauses5Error_pSgvp","extendedModule":"ExpoModulesCore","modules":[{"name":"ExpoModulesCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/rootCause-1u9cn"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException":{"role":"symbol","title":"ChainableException","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChainableException"}],"abstract":[{"type":"text","text":"An exception that may have been caused by another error."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChainableException"}],"url":"\/documentation\/expomodulescore\/chainableexception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/rootCause-38jk7":{"role":"symbol","title":"rootCause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The first error that started the chain of exceptions."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/rootCause-38jk7","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/rootcause-38jk7"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/rootCause-1u9cn":{"defaultImplementations":1,"role":"symbol","title":"rootCause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The first error that started the chain of exceptions."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/rootCause-1u9cn","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/rootcause-1u9cn"}}}