{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/exception\/causedby(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/causedBy(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the direct cause of the exception and returns itself."}],"kind":"symbol","metadata":{"role":"symbol","title":"causedBy(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"symbolKind":"method","externalID":"s:15ExpoModulesCore18ChainableExceptionPAAE8causedByyxs5Error_pSgF::SYNTHESIZED::s:15ExpoModulesCore9ExceptionC","extendedModule":"ExpoModulesCore","modules":[{"name":"ExpoModulesCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/ChainableException-Implementations"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception/ChainableException-Implementations":{"role":"collectionGroup","title":"ChainableException Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/ChainableException-Implementations","kind":"article","type":"topic","url":"\/documentation\/expomodulescore\/exception\/chainableexception-implementations"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception":{"role":"symbol","title":"Exception","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Exception"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Exception"}],"url":"\/documentation\/expomodulescore\/exception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception/causedBy(_:)":{"role":"symbol","title":"causedBy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets the direct cause of the exception and returns itself."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/causedBy(_:)","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/exception\/causedby(_:)"}}}