{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/exception\/rootcause"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/rootCause","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The first error that started the chain of exceptions."}],"kind":"symbol","metadata":{"role":"symbol","title":"rootCause","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:15ExpoModulesCore18ChainableExceptionPAAE9rootCauses5Error_pSgvp::SYNTHESIZED::s:15ExpoModulesCore9ExceptionC","extendedModule":"ExpoModulesCore","modules":[{"name":"ExpoModulesCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/ChainableException-Implementations"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception":{"role":"symbol","title":"Exception","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Exception"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Exception"}],"url":"\/documentation\/expomodulescore\/exception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception/ChainableException-Implementations":{"role":"collectionGroup","title":"ChainableException Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/ChainableException-Implementations","kind":"article","type":"topic","url":"\/documentation\/expomodulescore\/exception\/chainableexception-implementations"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception/rootCause":{"role":"symbol","title":"rootCause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The first error that started the chain of exceptions."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/rootCause","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/exception\/rootcause"}}}